name: Update Disposable Email List

on:
  schedule:
    - cron: "0 4 * * *"  # every day at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector script
        run: python src/collector.py
        continue-on-error: false

      - name: Commit and push changes
        run: |
          git config user.name "ghostmail-bot"
          git config user.email "bot@ghostmail.io"
          git add data/disposable_emails.txt
          git commit -m "Auto-update disposable email list" || echo "No changes to commit"
          git push